// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cmercury.h"

/////////////////////////////////////////////////////////////////////////////
// CMercury

IMPLEMENT_DYNCREATE(CMercury, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMercury properties

/////////////////////////////////////////////////////////////////////////////
// CMercury operations

void CMercury::Open()
{
	InvokeHelper(0xc9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::Close(BOOL ForceAbort)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xca, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ForceAbort);
}

void CMercury::OpenReceipt(long Oper)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Oper);
}

void CMercury::AddReceiptItem(LPCTSTR Desc, const CY& Price, BOOL ItemIsTare, long Department, long Code, long Adjustment, long Quantity, long QuantityPrec, long TaxIndex, LPCTSTR UnitName, long Flags)
{
	static BYTE parms[] =
		VTS_BSTR VTS_CY VTS_BOOL VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0xcc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Desc, &Price, ItemIsTare, Department, Code, Adjustment, Quantity, QuantityPrec, TaxIndex, UnitName, Flags);
}

void CMercury::CancelReceipt()
{
	InvokeHelper(0xcd, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::CloseReceipt(LPCTSTR Account, long PayType, const CY& PayCash, const CY& PayCashless, LPCTSTR PayInfo, long CopiesNum, long OperInfo)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_CY VTS_CY VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(0xce, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Account, PayType, &PayCash, &PayCashless, PayInfo, CopiesNum, OperInfo);
}

void CMercury::OpenCustomDoc(BOOL UseForm, long Oper)
{
	static BYTE parms[] =
		VTS_BOOL VTS_I4;
	InvokeHelper(0xcf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 UseForm, Oper);
}

void CMercury::CancelCustomDoc()
{
	InvokeHelper(0xd0, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::CloseCustomDoc(long PayType, long Flags, long HCopiesNum, long VCopiesNum, long VOrigOffset, long HCopyOffset, long VCopyOffset, long FiscalCopy)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xd1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PayType, Flags, HCopiesNum, VCopiesNum, VOrigOffset, HCopyOffset, VCopyOffset, FiscalCopy);
}

void CMercury::OpenFiscalDoc(long Oper)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xd2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Oper);
}

void CMercury::CancelFiscalDoc(BOOL BufferOnly)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xd3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 BufferOnly);
}

void CMercury::PrintFiscalDocBuffer()
{
	InvokeHelper(0xd4, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::CloseFiscalDoc()
{
	InvokeHelper(0xd5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::CopyFiscalDoc()
{
	InvokeHelper(0xd6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::AddSerialNumber(long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xd7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset);
}

void CMercury::AddHeaderLine(long LineNum, long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xd8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 LineNum, Flags, HOffset, VOffset);
}

void CMercury::AddDateTime(long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xd9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset);
}

void CMercury::AddOperInfo(long OperInfo, long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xda, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 OperInfo, Flags, HOffset, VOffset);
}

void CMercury::AddDocNumber(long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xdb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset);
}

void CMercury::AddReceiptNumber(long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xdc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset);
}

void CMercury::AddAccount(LPCTSTR Account, long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xdd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Account, Flags, HOffset, VOffset);
}

void CMercury::AddTaxPayerNumber(long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xde, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset);
}

void CMercury::AddItem(long ItemType, const CY& Price, BOOL ItemIsTare, long Department, long Code, long Adjustment, long Quantity, long QuantityPrec, long TaxIndex, LPCTSTR UnitName, long Flags, long HOffset, long VOffset, long RightOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_CY VTS_BOOL VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xdf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ItemType, &Price, ItemIsTare, Department, Code, Adjustment, Quantity, QuantityPrec, TaxIndex, UnitName, Flags, HOffset, VOffset, RightOffset);
}

void CMercury::AddDocPercentAdj(long Value, long TaxIndex, long Flags, long HOffset, long VOffset, long RightOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe0, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Value, TaxIndex, Flags, HOffset, VOffset, RightOffset);
}

void CMercury::AddDocAmountAdj(const CY& Value, long TaxIndex, long Flags, long HOffset, long VOffset, long RightOffset)
{
	static BYTE parms[] =
		VTS_CY VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Value, TaxIndex, Flags, HOffset, VOffset, RightOffset);
}

void CMercury::AddTotal(long Flags, long HOffset, long VOffset, long RightOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset, RightOffset);
}

void CMercury::AddPay(long PayType, const CY& PayCash, const CY& PayCashless, LPCTSTR PayInfo, long Flags, long HOffset, long VOffset, long RightOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_CY VTS_CY VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PayType, &PayCash, &PayCashless, PayInfo, Flags, HOffset, VOffset, RightOffset);
}

void CMercury::AddChange(long Flags, long HOffset, long VOffset, long RightOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset, RightOffset);
}

void CMercury::AddTaxSum(long TaxIndex, long Flags, long HOffset, long VOffset, long RightOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 TaxIndex, Flags, HOffset, VOffset, RightOffset);
}

void CMercury::AddFiscalSign(long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset);
}

void CMercury::AddBarcode(long Mask1, long Mask2, long Mask3, long Mask4, long Mask5, BOOL DoubleDensity, long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BOOL VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Mask1, Mask2, Mask3, Mask4, Mask5, DoubleDensity, Flags, HOffset, VOffset);
}

void CMercury::AddCustom(LPCTSTR Text, long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Text, Flags, HOffset, VOffset);
}

void CMercury::RepeatOperation()
{
	InvokeHelper(0xe9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::OpenDay(long OperNum, LPCTSTR OperName, BOOL FullJournal, long AProtocol)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_BOOL VTS_I4;
	InvokeHelper(0xea, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 OperNum, OperName, FullJournal, AProtocol);
}

long CMercury::ZReport(long Flags)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xeb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Flags);
	return result;
}

long CMercury::FiscalRewrite(LPCTSTR InspPswd, LPCTSTR RegNum, LPCTSTR TaxPayerNum, LPCTSTR NewInspPswd)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0xec, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		InspPswd, RegNum, TaxPayerNum, NewInspPswd);
	return result;
}

long CMercury::FiscalReportByNum(LPCTSTR InspPswd, BOOL PrintFull, long AStartNum, long AEndNum)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_I4 VTS_I4;
	InvokeHelper(0xed, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		InspPswd, PrintFull, AStartNum, AEndNum);
	return result;
}

long CMercury::FiscalReportByDate(LPCTSTR InspPswd, BOOL PrintFull, DATE AStartDate, DATE AEndDate)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_DATE VTS_DATE;
	InvokeHelper(0xee, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		InspPswd, PrintFull, AStartDate, AEndDate);
	return result;
}

long CMercury::FiscalReportAll(LPCTSTR InspPswd)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xef, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		InspPswd);
	return result;
}

void CMercury::FeedAndCut(long LineCount, BOOL CutAfterFeed)
{
	static BYTE parms[] =
		VTS_I4 VTS_BOOL;
	InvokeHelper(0xf0, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 LineCount, CutAfterFeed);
}

void CMercury::PrintNonFiscal(LPCTSTR Data, BOOL OpenDoc, BOOL CloseDoc)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_BOOL;
	InvokeHelper(0xf1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Data, OpenDoc, CloseDoc);
}

void CMercury::ShowDisplay(LPCTSTR Data, BOOL OpenMode, BOOL CloseMode)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL VTS_BOOL;
	InvokeHelper(0xf2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Data, OpenMode, CloseMode);
}

void CMercury::SetDisplayBaudRate(long BaudRate)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xf3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 BaudRate);
}

void CMercury::ExternalPulse(long Channel, long TimeOn, long TimeOff, long Count)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xf4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Channel, TimeOn, TimeOff, Count);
}

void CMercury::QueryDevExStatus()
{
	InvokeHelper(0xf5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::QueryFirmwareInfo()
{
	InvokeHelper(0xf6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::SetHeader(LPCTSTR Line1, LPCTSTR Line2, LPCTSTR Line3, LPCTSTR Line4)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0xf7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Line1, Line2, Line3, Line4);
}

void CMercury::SetTax(long Index, LPCTSTR TaxName, long TaxRate)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0xf8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Index, TaxName, TaxRate);
}

long CMercury::QueryTax(long Index)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xf9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Index);
	return result;
}

CY CMercury::QueryCounter(long Index, BOOL NoRequest)
{
	CY result;
	static BYTE parms[] =
		VTS_I4 VTS_BOOL;
	InvokeHelper(0xfa, DISPATCH_METHOD, VT_CY, (void*)&result, parms,
		Index, NoRequest);
	return result;
}

void CMercury::SynchronizeEcrDateTime()
{
	InvokeHelper(0xfb, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::QueryResourceInfo(BOOL PrintInfo)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PrintInfo);
}

void CMercury::QueryLastDocInfo()
{
	InvokeHelper(0xfd, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::SetParameters(long Protocol, long PrnTimeout)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xfe, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Protocol, PrnTimeout);
}

long CMercury::GetEcrModel()
{
	long result;
	InvokeHelper(0xff, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetEcrVersion()
{
	long result;
	InvokeHelper(0x100, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetGeneration()
{
	long result;
	InvokeHelper(0x101, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetProtocol()
{
	long result;
	InvokeHelper(0x102, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetEcrStatus()
{
	long result;
	InvokeHelper(0x103, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetEcrStatusMask()
{
	long result;
	InvokeHelper(0x104, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetDevStatus()
{
	long result;
	InvokeHelper(0x105, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetDevStatusMask()
{
	long result;
	InvokeHelper(0x106, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetDocStatus()
{
	long result;
	InvokeHelper(0x107, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetCurrentOper()
{
	long result;
	InvokeHelper(0x108, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetPortNum()
{
	long result;
	InvokeHelper(0x109, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CMercury::SetPortNum(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x109, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CMercury::GetBaudRate()
{
	long result;
	InvokeHelper(0x10a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CMercury::SetBaudRate(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x10a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString CMercury::GetPassword()
{
	CString result;
	InvokeHelper(0x10b, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CMercury::SetPassword(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x10b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

long CMercury::GetInternalTimeout()
{
	long result;
	InvokeHelper(0x10c, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CMercury::SetInternalTimeout(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x10c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CMercury::GetExternalTimeout()
{
	long result;
	InvokeHelper(0x10d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CMercury::SetExternalTimeout(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x10d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString CMercury::QueryHeaderLine(long LineNum)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x10e, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		LineNum);
	return result;
}

CString CMercury::QuerySerialNumber()
{
	CString result;
	InvokeHelper(0x10f, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CMercury::SetSerialNumber(LPCTSTR Value)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x110, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Value);
}

CString CMercury::QueryTaxPayerNumber()
{
	CString result;
	InvokeHelper(0x111, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::QueryRegNumber()
{
	CString result;
	InvokeHelper(0x112, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

DATE CMercury::QueryEcrDateTime()
{
	DATE result;
	InvokeHelper(0x113, DISPATCH_METHOD, VT_DATE, (void*)&result, NULL);
	return result;
}

CString CMercury::QueryDepartName(long DepartNum)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x114, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		DepartNum);
	return result;
}

void CMercury::SetDepartName(long DepartNum, LPCTSTR Value)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x115, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 DepartNum, Value);
}

CString CMercury::QueryTitle(long TitleNum)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x116, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		TitleNum);
	return result;
}

void CMercury::SetTitle(long TitleNum, LPCTSTR Value)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x117, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 TitleNum, Value);
}

BOOL CMercury::GetActive()
{
	BOOL result;
	InvokeHelper(0x118, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CMercury::SetActive(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x118, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

long CMercury::GetConnState()
{
	long result;
	InvokeHelper(0x119, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CY CMercury::GetSaleSum()
{
	CY result;
	InvokeHelper(0x11a, DISPATCH_PROPERTYGET, VT_CY, (void*)&result, NULL);
	return result;
}

CY CMercury::GetBuyingSum()
{
	CY result;
	InvokeHelper(0x11b, DISPATCH_PROPERTYGET, VT_CY, (void*)&result, NULL);
	return result;
}

CString CMercury::GetSerialNumber()
{
	CString result;
	InvokeHelper(0x11c, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::GetRegNumber()
{
	CString result;
	InvokeHelper(0x11d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::GetTaxPayerNumber()
{
	CString result;
	InvokeHelper(0x11e, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::GetHeaderLine1()
{
	CString result;
	InvokeHelper(0x11f, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::GetHeaderLine2()
{
	CString result;
	InvokeHelper(0x120, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::GetHeaderLine3()
{
	CString result;
	InvokeHelper(0x121, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::GetHeaderLine4()
{
	CString result;
	InvokeHelper(0x122, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

DATE CMercury::GetStartDate()
{
	DATE result;
	InvokeHelper(0x123, DISPATCH_PROPERTYGET, VT_DATE, (void*)&result, NULL);
	return result;
}

DATE CMercury::GetEndDate()
{
	DATE result;
	InvokeHelper(0x124, DISPATCH_PROPERTYGET, VT_DATE, (void*)&result, NULL);
	return result;
}

long CMercury::GetStartNumber()
{
	long result;
	InvokeHelper(0x125, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetEndNumber()
{
	long result;
	InvokeHelper(0x126, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

DATE CMercury::GetReportDate()
{
	DATE result;
	InvokeHelper(0x127, DISPATCH_PROPERTYGET, VT_DATE, (void*)&result, NULL);
	return result;
}

CString CMercury::GetModelName()
{
	CString result;
	InvokeHelper(0x128, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::GetManufacturer()
{
	CString result;
	InvokeHelper(0x129, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::GetFirmwareVersion()
{
	CString result;
	InvokeHelper(0x12a, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CMercury::GetTaxName()
{
	CString result;
	InvokeHelper(0x12b, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

DATE CMercury::GetTaxDate()
{
	DATE result;
	InvokeHelper(0x12c, DISPATCH_PROPERTYGET, VT_DATE, (void*)&result, NULL);
	return result;
}

long CMercury::GetCounterCount()
{
	long result;
	InvokeHelper(0x12d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetRewritesRemain()
{
	long result;
	InvokeHelper(0x12e, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetDaysRemain()
{
	long result;
	InvokeHelper(0x12f, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetLastFiscalReport()
{
	long result;
	InvokeHelper(0x130, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetLastDayClosing()
{
	long result;
	InvokeHelper(0x131, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

DATE CMercury::GetDayDate()
{
	DATE result;
	InvokeHelper(0x132, DISPATCH_PROPERTYGET, VT_DATE, (void*)&result, NULL);
	return result;
}

long CMercury::GetLastDocOper()
{
	long result;
	InvokeHelper(0x133, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetLastDocNumber()
{
	long result;
	InvokeHelper(0x134, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetLastRecNumber()
{
	long result;
	InvokeHelper(0x135, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetLastDocType()
{
	long result;
	InvokeHelper(0x136, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CY CMercury::GetLastDocSum()
{
	CY result;
	InvokeHelper(0x137, DISPATCH_PROPERTYGET, VT_CY, (void*)&result, NULL);
	return result;
}

DATE CMercury::GetLastDocDate()
{
	DATE result;
	InvokeHelper(0x138, DISPATCH_PROPERTYGET, VT_DATE, (void*)&result, NULL);
	return result;
}

BOOL CMercury::GetRetryOperation()
{
	BOOL result;
	InvokeHelper(0x139, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CMercury::SetRetryOperation(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x139, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

long CMercury::GetErrCode()
{
	long result;
	InvokeHelper(0x13a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetErrCodeEx()
{
	long result;
	InvokeHelper(0x13b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CString CMercury::GetErrMessage()
{
	CString result;
	InvokeHelper(0x13c, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CMercury::CheckEcrStatus(long Flag)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x13d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Flag);
	return result;
}

long CMercury::CheckDevStatus(long Flag)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x13e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Flag);
	return result;
}

long CMercury::GetEcrHour()
{
	long result;
	InvokeHelper(0x13f, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetEcrMin()
{
	long result;
	InvokeHelper(0x140, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetReportHour()
{
	long result;
	InvokeHelper(0x141, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetReportMin()
{
	long result;
	InvokeHelper(0x142, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetDayHour()
{
	long result;
	InvokeHelper(0x143, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetDayMin()
{
	long result;
	InvokeHelper(0x144, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetLastDocHour()
{
	long result;
	InvokeHelper(0x145, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetLastDocMin()
{
	long result;
	InvokeHelper(0x146, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CMercury::AddGraphicHeader(long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x147, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset);
}

void CMercury::SetProtocol(long Protocol)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x148, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Protocol);
}

void CMercury::SetPrinterTimeout(long Timeout)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x149, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Timeout);
}

void CMercury::SetDisplayTimeout(long Timeout)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x14a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Timeout);
}

void CMercury::SetPrinterContrast(long Contrast)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x14b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Contrast);
}

void CMercury::SetLeading(long Leading)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x14c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Leading);
}

void CMercury::SetCutterDisabled(BOOL Disabled)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x14d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Disabled);
}

void CMercury::SetNarrowPaper(BOOL Narrow)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x14e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Narrow);
}

long CMercury::QueryPrinterTimeout()
{
	long result;
	InvokeHelper(0x14f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::QueryDisplayTimeout()
{
	long result;
	InvokeHelper(0x150, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::QueryPrinterContrast()
{
	long result;
	InvokeHelper(0x151, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::QueryLeading()
{
	long result;
	InvokeHelper(0x152, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CMercury::EnableGraphicHeader(long Width, long Height, LPCTSTR Data)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x153, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Width, Height, Data);
}

void CMercury::DisableGraphicHeader()
{
	InvokeHelper(0x154, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::AddLicence(long LicType, LPCTSTR Licence)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x155, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 LicType, Licence);
}

long CMercury::XReport(long Flags)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x156, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Flags);
	return result;
}

long CMercury::XReportByDep(long DepartNum, long Flags)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x157, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		DepartNum, Flags);
	return result;
}

long CMercury::XReportByOper(long OperNum, long Flags)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x158, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		OperNum, Flags);
	return result;
}

BOOL CMercury::QueryHeaderAlignment()
{
	BOOL result;
	InvokeHelper(0x159, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

long CMercury::QueryOperNumber()
{
	long result;
	InvokeHelper(0x15a, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CMercury::QueryOperName(long OperNum)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x15b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		OperNum);
	return result;
}

void CMercury::SetHeaderAlignment(BOOL Aligned)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x15c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Aligned);
}

void CMercury::TestConnection()
{
	InvokeHelper(0x15d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CMercury::GetVersionNumber()
{
	long result;
	InvokeHelper(0x15e, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CMercury::GetBuildNumber()
{
	long result;
	InvokeHelper(0x15f, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CString CMercury::GetVersion()
{
	CString result;
	InvokeHelper(0x160, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CMercury::SetVersion(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x160, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

long CMercury::GetBorderSize()
{
	long result;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CMercury::SetBorderSize(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3e9, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

BOOL CMercury::GetShowState()
{
	BOOL result;
	InvokeHelper(0x3ea, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CMercury::SetShowState(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x3ea, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CMercury::GetEnabled()
{
	BOOL result;
	InvokeHelper(DISPID_ENABLED, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CMercury::SetEnabled(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(DISPID_ENABLED, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

void CMercury::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CMercury::QueryAutocut()
{
	BOOL result;
	InvokeHelper(0x161, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CMercury::SetAutocut(BOOL Autocut)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x162, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Autocut);
}

BOOL CMercury::QueryEconomicMode()
{
	BOOL result;
	InvokeHelper(0x163, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CMercury::SetEconomicMode(BOOL EconomicMode)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x164, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 EconomicMode);
}

long CMercury::GetEcrSubVersion()
{
	long result;
	InvokeHelper(0x165, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CMercury::EKLZActivate()
{
	InvokeHelper(0x191, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::EKLZActivationReport()
{
	InvokeHelper(0x192, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::EKLZDayReport(long DayNumber)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x193, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 DayNumber);
}

void CMercury::EKLZReportByNum(BOOL IsFull, long AStartNum, long AEndNum)
{
	static BYTE parms[] =
		VTS_BOOL VTS_I4 VTS_I4;
	InvokeHelper(0x194, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 IsFull, AStartNum, AEndNum);
}

void CMercury::EKLZReportByDate(BOOL IsFull, DATE AStartDate, DATE AEndDate)
{
	static BYTE parms[] =
		VTS_BOOL VTS_DATE VTS_DATE;
	InvokeHelper(0x195, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 IsFull, AStartDate, AEndDate);
}

void CMercury::EKLZDocByNum(long Number)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x196, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Number);
}

void CMercury::EKLZControlByNum(long DayNumber)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x197, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 DayNumber);
}

void CMercury::EKLZCloseArchive()
{
	InvokeHelper(0x198, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::EKLZQueryStatus()
{
	InvokeHelper(0x199, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CMercury::QueryPaperJournal()
{
	BOOL result;
	InvokeHelper(0x19a, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CMercury::SetPaperJournal(BOOL PaperJournal)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x19b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PaperJournal);
}

BOOL CMercury::GetEKLZSupported()
{
	BOOL result;
	InvokeHelper(0x19c, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CMercury::GetEKLZActivated()
{
	BOOL result;
	InvokeHelper(0x19d, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

long CMercury::GetEKLZOper()
{
	long result;
	InvokeHelper(0x19e, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CMercury::GetEKLZArchiving()
{
	BOOL result;
	InvokeHelper(0x19f, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CMercury::GetEKLZReporting()
{
	BOOL result;
	InvokeHelper(0x1a0, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CMercury::GetEKLZDayOpened()
{
	BOOL result;
	InvokeHelper(0x1a1, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CMercury::GetEKLZFatalError()
{
	BOOL result;
	InvokeHelper(0x1a2, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CMercury::GetEKLZAttention()
{
	BOOL result;
	InvokeHelper(0x1a3, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CMercury::QueryFullJournal()
{
	BOOL result;
	InvokeHelper(0x1f5, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CMercury::SetFullJournal(BOOL FullJournal)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x1f6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 FullJournal);
}

void CMercury::AddEKLZData(long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x1f7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset);
}

CY CMercury::GetLastBuyingSum()
{
	CY result;
	InvokeHelper(0x1f8, DISPATCH_PROPERTYGET, VT_CY, (void*)&result, NULL);
	return result;
}

void CMercury::AddRegNumber(long Flags, long HOffset, long VOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x259, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Flags, HOffset, VOffset);
}

void CMercury::WriteGraphic(long Number, long Width, long Height, LPCTSTR Data)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x2bd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Number, Width, Height, Data);
}

void CMercury::PrintGraphic(long Width, long Height, LPCTSTR Data)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x2be, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Width, Height, Data);
}

BOOL CMercury::QueryParameterBool(long ParamCode)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x321, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		ParamCode);
	return result;
}

long CMercury::QueryParameterInt(long ParamCode)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x322, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ParamCode);
	return result;
}

void CMercury::SetParameterBool(long ParamCode, BOOL ParamValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BOOL;
	InvokeHelper(0x323, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ParamCode, ParamValue);
}

void CMercury::SetParameterInt(long ParamCode, long ParamValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x324, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ParamCode, ParamValue);
}

void CMercury::PrintHeader()
{
	InvokeHelper(0x385, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMercury::SetOperPassword(long OperNum, LPCTSTR OperName, LPCTSTR OperPassword)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3eb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 OperNum, OperName, OperPassword);
}

long CMercury::PrintEKL(long Flags)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x44d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Flags);
	return result;
}

long CMercury::QueryEKLState()
{
	long result;
	InvokeHelper(0x44e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CMercury::ReprintDocument()
{
	InvokeHelper(0x4b1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
BOOL CMercury::CreateFromStatic(UINT nID, CWnd *pParent)
{
	CStatic wndStatic;
	if(!wndStatic.SubclassDlgItem (nID,pParent))
		return FALSE;
	CRect rc;
	DWORD dwStyle=wndStatic.GetStyle ();
	wndStatic.GetWindowRect (&rc);
	pParent->ScreenToClient (&rc);
	wndStatic.DestroyWindow ();
	this->nID =nID;
	return Create(NULL,dwStyle,rc,pParent,nID);
}

void CMercury::PrintCheck(IUnknown *pUnk,double dblCash)
{
int flags = 0;
	int iv = 0;

		OpenFiscalDoc(1);							// открытие обычного чека
	// Для ККМ, не поддерживающих упреждающую печать заголовка добавляем строки
  // клише в чек явным образом
  if(GetGeneration() != 7 || GetEcrSubVersion() < 0x0300)
  {
    for(int I = 1; I <= 4; I++)
      AddHeaderLine(I, 0, 0, iv++);
  }
  else
  {
    // Если ККМ поддерживает упреждающую печать заголовка, то проверяем, печать
    // каких строк клише включена
    int PrintNeeded[5];
    PrintNeeded[1] = QueryParameterBool(16 /* MERC_PARAM_AUTOHEADER_LINE1 */);
    PrintNeeded[2] = QueryParameterBool(17 /* MERC_PARAM_AUTOHEADER_LINE2 */);
    PrintNeeded[3] = QueryParameterBool(18 /* MERC_PARAM_AUTOHEADER_LINE3 */);
    PrintNeeded[4] = QueryParameterBool(19 /* MERC_PARAM_AUTOHEADER_LINE4 */);
    // Если упреждающая печать выключена для всех строк, то добавляем строки
    // клише в чек явным образом
    if(!PrintNeeded[1] && !PrintNeeded[2] && !PrintNeeded[3] && !PrintNeeded[4])
    {
      for(int I = 1; I <= 4; I++)
        AddHeaderLine(I, 0, 0, iv++);
    }
    else
    {
      // Если включена упреждающая печать, то проверяем, есть ли ненапечатанные
      // строки клише; если есть - печатаем заголовок чека вызовом метода
      // PrintHeader (метод напечатает только те строки, для которых включена
      // упреждающая печать); счетчик строк iv здесь в любом случае увеличивать
      // не нужно, т.к. заголовок не входит в состав чека
      for(int I = 1; I < 4; I++)
      {
        if(PrintNeeded[I] &&
           !QueryParameterBool(20 /* MERC_PARAM_HEADER_PRINTED_LINE1 */ + I - 1)
          )
        {
          PrintHeader();
          break;
        }
      }
    }
  }
		AddSerialNumber(flags, 0, iv++);			// печать серийного номера ККМ
		AddDateTime(flags, 0, iv++);				// печать текущих даты и времени
		AddOperInfo(0, flags, 0, iv++);			// печать информации об операторе
		AddDocNumber(flags, 0, iv++);				// печать номера документа
		AddAccount(_T (""), flags, 0, iv++);		// печать номера счета
		AddReceiptNumber(flags, 0, iv++);			// печать номера документа
		AddTaxPayerNumber(flags, 0, iv++);		// печать ИНН
		IVSFlexGridPtr pGrid=pUnk;

 	for(long i=1;i<pGrid->GetRows();i++)
	{
		
		
	
		//печать комментария к услуге
	AddCustom(
				(LPCTSTR)pGrid->GetTextMatrix (i,2),		// строка текста
				16 + 64 + flags, 		// флаги шрифта
				0,						// смещение по горизонтали
				iv++					// смещение по вертикали
				);
		//печать реквизита цены
		COleCurrency cyPrice;
		cyPrice.ParseCurrency ((LPCTSTR)pGrid->GetTextMatrix (i,3));
		int nQty=_ttoi((LPCTSTR)pGrid->GetTextMatrix (i,5));
		
		AddItem(
				0,					// операция услуга, товар или денежная сумма
				cyPrice.m_cur ,			// цена услуги
				FALSE,				// услуга не является тарой
				1,					// номер отдела
				0,					// код товара
				1000,				// значение процентной скидки/надбавки
				nQty*100,				// количество товаров или услуг
				2,					// число значащих цифр после запятой для количества
				0,
				_T("шт"),				// наименование единицы измерения
				flags,				// флаги шрифта
				0, 					// смещение по горизонтали
				iv++, 				// смещение по вертикали
				0					// смещение правой части относительно левого края чека
				);
	}
		// печать полной суммы чека
		AddTotal(flags, 0, iv++, 0);
		// печать уплаченной суммы
		COleCurrency cyCash;
		CY cyCashless;
		cyCash=(_variant_t)dblCash;
		cyCashless.int64 = (__int64) 0;
		AddPay(
					0,					// тип оплаты - наличные
					cyCash,				// сумма наличных
					cyCashless,			// сумма безналичных
					_T (""), 			// дополнительная информация при безналичном расчете
					flags,				// флаги шрифта
					0,					// смещение по горизонтали
					iv++,				// смещение по вертикали
					0					// смещение правой части);
					);
		// печать сдачи
		AddChange(flags, 0, iv++, 0);
	
		// закрытие печати чека
		CloseFiscalDoc();
	

}
