//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UserThreads.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_USERTHREADS_FORM            101
#define IDR_NAKLFORM_TMPL               102
#define IDR_DICTFORM_TMPL               103
#define ID_WINDOW_CLOSE                 104
#define ID_WINDOW_CLOSE_ALL             105
#define ID_WINDOW_NEXT                  106
#define ID_WINDOW_PREVIOUS              107
#define ID_WINDOW_MANAGE                108
#define IDC_GOODS_GRID                  110
#define IDC_CATEGORY_TREE               111
#define IDC_FONTNAME_CB                 112
#define IDC_FONTSIZE_CB                 113
#define IDS_CHECK_BUTTON_LABEL          114
#define IDD_FIND_DLG1                   115
#define IDS_SELECT_DLG_CAPTION          115
#define IDR_FINDVIEW_TMPL               116
#define ID_INDICATOR_ROWS               117
#define ID_INDICATOR_LANG               118
#define ID_DEARCHIVE                    119
#define IDS_BUILD_TAB                   119
#define IDR_USERTHREADS                 120
#define IDS_DEBUG_TAB                   120
#define IDR_BARCODEREADER               121
#define IDS_FIND_TAB                    121
#define IDC_TIPWND                      122
#define ID_CHECK                        123
#define ID_ZREPORT                      124
#define ID_UNDOALLGOODS                 125
#define IDC_INFONUMRETURN               126
#define IDC_INFOBASERETURN              127
#define IDR_MAINFRAME                   128
#define IDC_INFONPOSRETURN              128
#define IDR_USERTHTYPE                  129
#define IDR_MDIUSERTH                   129
#define IDC_INFONUNITSRETURN            129
#define IDR_INFOFRAME                   130
#define IDC_INFOSUMMARETURN             130
#define ID_PANE_COMPORT                 131
#define IDD_DICT_DLG                    132
#define ID_PANE_PA                      132
#define IDD_NAKL_DLG                    133
#define IDC_GRID_GJ                     133
#define ID_INDICATOR_1C                 134
#define IDR_INFO_TOOLBAR                135
#define ID_PANE_KKM                     135
#define ID_ENTER_MULTIPLICATOR          136
#define IDI_OPENFOLDERS                 139
#define IDI_CLOSEFOLDERS                140
#define IDI_OPENING                     141
#define IDI_CLOSEFOLDER                 142
#define IDB_FOLDERS                     146
#define IDI_FIND                        147
#define IDI_QUEST                       148
#define IDR_FONTTBAR                    151
#define IDB_SPLASH                      153
#define IDB_FOLDER                      156
#define IDI_FOLDER                      158
#define IDB_BITMAP1                     159
#define IDD_SET_PERIOD                  161
#define IDD_FIND_DLG                    163
#define ID_DLG_TOOLBAR                  164
#define IDC_CURSOR1                     166
#define IDD_EXPL_DLG                    167
#define IDI_ARCHIVE                     169
#define IDI_ARRUP                       170
#define IDI_ARRDOWN                     171
#define IDI_NOMENCLATURA                172
#define IDR_POPUP                       173
#define IDI_JOURNAL                     174
#define IDD_DLGCOMPORT                  175
#define ID_INSERT                       177
#define ID_RECIC                        178
#define ID_DELETE                       179
#define ID_TOOL                         180
#define IDI_ICON2                       181
#define IDB_TOOLBAR1                    182
#define IDB_TOOLBAR2                    183
#define IDB_TOOLBAR1_32                 184
#define IDD_DLGINSERT                   185
#define IDB_ICONS                       188
#define IDD_SELGOOD                     189
#define IDI_FOLDERSFILE                 190
#define IDI_BARCODE                     191
#define IDI_ISTRANSACTED                192
#define IDI_ADDINDOCUMENT               193
#define IDI_COPY                        194
#define IDI_GOOD                        195
#define IDI_GOOD_TB                     195
#define IDD_SETQTY                      196
#define IDD_FINDALL                     197
#define IDD_DLGCHANGE                   198
#define IDD_LOGIN                       199
#define IDD_RETURN                      203
#define IDD_RECICLING                   204
#define IDR_RETURN                      205
#define IDR_ANIMATION                   209
#define IDI_SELDOC                      211
#define IDI_SELDOC1                     212
#define IDI_CALENDAR                    213
#define IDI_SELGOOD                     214
#define IDI_OK                          215
#define IDI_SELSALEDOC                  216
#define IDR_SELGOODSTB                  217
#define IDI_RIGHTARROW                  220
#define IDI_DBLRIGHTARROW               222
#define IDI_DBLLEFTARROW                223
#define IDD_DLGSELDATE                  224
#define IDI_DOCNOTRANSACT               225
#define IDI_DOCTRANSACT                 226
#define IDI_ACCOUNT                     227
#define IDI_GOOD_GRD                    228
#define IDD_ZREPORT                     229
#define IDR_GENJOURNAL_TB               230
#define IDI_INTERVAL                    232
#define IDI_DOCVIEW                     233
#define IDD_FIRSTSTEP                   234
#define IDD_SECONDSTEP                  235
#define IDD_THIRDSTEP                   236
#define IDB_BITMAP2                     239
#define IDB_BMPFS                       240
#define IDB_BITMAP3                     241
#define IDI_1C                          243
#define IDD_DLGKKM                      244
#define IDD_MULQTY                      245
#define IDI_DELETE                      247
#define IDR_OUTPUT_POPUP                250
#define IDR_TOOLBAR1                    251
#define IDB_BITMAP4                     253
#define IDB_BITMAP5                     254
#define IDR_MULTTOOLBAR                 255
#define IDD_FONTDLG                     257
#define IDC_TREE1                       1002
#define IDC_DATETIMEPICKER1             1003
#define IDC_STATIC3                     1004
#define IDC_INFO_ABOUT_CHECK            1006
#define IDC_GRID                        1007
#define ID_NEXT_FIELD                   1007
#define IDC_ST_NUM_CHECK                1008
#define IDC_ST_NUM_POS                  1009
#define IDC_ST_SUMM                     1010
#define IDC_ST_CLIENT                   1011
#define IDC_DTPICKER1                   1013
#define IDC_DTPICKER2                   1014
#define IDC_BUTTON1                     1016
#define IDC_FINDBTN                     1016
#define IDC_BTNSELDOC                   1016
#define IDC_7NUM                        1016
#define IDC_GETDIGIT                    1016
#define IDC_RADIO_ALL                   1017
#define IDC_8NUM                        1017
#define IDC_SET_FNT                     1017
#define IDC_RADIO_CUSTOM                1018
#define IDC_9NUM                        1018
#define IDC_4NUM                        1019
#define IDC_FIND                        1020
#define IDC_5NUM                        1020
#define IDC_STATIC1                     1021
#define IDC_6NUM                        1021
#define IDC_STATIC2                     1022
#define IDC_1NUM                        1022
#define IDC_2NUM                        1023
#define IDC_3NUM                        1024
#define IDC_CLEAR                       1025
#define IDC_COMBOEX                     1026
#define IDC_0NUM                        1026
#define IDC_BACKSPC                     1027
#define IDC_SQL                         1028
#define IDC_COMPORTLIST                 1029
#define IDC_EDIT                        1030
#define IDC_GRID1                       1031
#define IDC_GRID2                       1032
#define IDC_EDIT1                       1033
#define IDC_GRID3                       1034
#define IDC_EDIT3                       1035
#define IDC_CHANGE                      1036
#define IDC_LABEL                       1039
#define IDC_CASH                        1040
#define IDC_CBUSERS                     1041
#define IDC_PASSWORD                    1042
#define IDC_DOCLIST                     1043
#define IDC_ENTRYDOC                    1044
#define IDC_RETGOODS                    1045
#define IDC_BTNEXEC                     1048
#define IDC_INFO                        1049
#define IDC_BTNPODBOR                   1050
#define IDC_TOOLBARPLACE                1052
#define IDC_MONTHCALENDAR1              1053
#define IDC_LBL_OSTATOK                 1054
#define IDC_LBL_SUMSALE                 1055
#define IDC_LBL_SUMRETURN               1056
#define IDC_CAPTION                     1057
#define IDC_LBL_CURSUMMA                1058
#define IDC_TOOLBARPLACE1               1058
#define IDC_STATICFP                    1059
#define IDC_FSBEGAMOUNT                 1061
#define IDC_FSENDAMOUNT                 1062
#define IDC_FSEMPLOYER                  1063
#define IDC_FSOKLAD                     1064
#define IDC_FSPREMIA                    1065
#define IDC_SSSALER                     1065
#define IDC_FSITOGO                     1066
#define IDC_SSOSTATOK                   1066
#define IDC_SSZARPLATA                  1067
#define IDC_SSZABRAL                    1068
#define IDC_FSKASSA                     1069
#define IDC_EDZABRAL                    1069
#define IDC_SSOSTEND                    1070
#define IDC_BEGAMOUNT                   1070
#define IDC_ENDAMOUNT                   1071
#define IDC_EDZABRAL2                   1071
#define IDC_GRIDZREPORT                 1071
#define IDC_CASHVAL                     1072
#define IDC_SSCASHMOVE                  1072
#define IDC_FOLDERTAB                   1072
#define IDC_SALARY                      1073
#define IDC_SSCASHOSTEND                1073
#define IDC_CHECK_KKMON                 1073
#define IDC_ZABRAL                      1074
#define IDC_SSCASHNOW                   1074
#define IDC_ED_PATH1C                   1074
#define IDC_SDANO                       1075
#define IDC_1CPASSWORD                  1075
#define IDC_OSTATOK                     1076
#define IDC_MERCURY                     1076
#define IDC_SALER                       1077
#define IDC_BTN_FIND                    1078
#define IDC_FNDDLG_SHOW                 1079
#define IDC_TRANSACT                    1080
#define IDC_KKM_INFO                    1081
#define IDC_COM_KKM                     1082
#define IDC_STATUS_KKM                  1083
#define IDC_SAMPLE_FONT                 1083
#define IDC_BTN_SEL_FNT                 1084
#define IDC_FONT_DESCR                  1085
#define IDC_LST_FONTS                   1086
#define ID_PREV_FIELD                   10008
#define ID_RETURN                       10009
#define ID_VIEW_INFOCONSOLE             32771
#define ID_VIEW_VIEWTAB                 32771
#define ID_FILE_NAKLAD                  32772
#define ID_FILE_DICTIONARY              32773
#define ID_FINDGOODS                    32780
#define ID_BUTTON32781                  32781
#define ID_BUTTON32782                  32782
#define ID_FONT_BOLD                    32783
#define ID_FONT_ITALIC                  32784
#define ID_SET_PERIOD                   32785
#define ID_FIND_VIEW_SHOW               32786
#define ID_FOLDER_VIEW_SHOW             32789
#define IDC_ARCHIVE                     32790
#define ID_CUSTOMIZE                    32793
#define ID_ACCEL32795                   32795
#define ID_SELSALEDOC                   32796
#define ID_DATESELECT                   32797
#define ID_SELGOOD                      32799
#define ID_EXECRETURN                   32800
#define ID_SEL1GOOD                     32801
#define ID_SELALLGOODS                  32802
#define ID_PREVIEW_DOC                  32803
#define ID_SETINTERVAL                  32804
#define ID_FINDDOC                      32805
#define ID_RETURNED                     -32730
#define ID_ACCEL32807                   32807
#define ID_ACCEL32808                   32808
#define ID_MULTBUT_HOLDER               32809
#define ID_REFRESH_CATALOG              32810
#define ID_MONIKER                      32811
#define ID_POPUP_COPY                   32818
#define ID_POPUP_CLEAR                  32819
#define ID_POPUP_HIDE                   32820
#define ID_VIEW_OUTPUTWND               32821
#define ID_BUTTON32822                  32822
#define ID_BUTTON32823                  32823
#define ID_BUTTON32824                  32824
#define ID_BUTTON32825                  32825
#define ID_BUTTON32826                  32826
#define IDR_FOLDERTABS                  57346
#define IDS_LABEL_TOOLBARM              61204
#define IDS_GOODPROP_QUERY              61205
#define IDS_GOODPROP_FILTER             61206
#define IDS_QUERY_GOODS_FROM_PARTID     61207
#define IDS_FILTER_GOODS_FROM_PARTID    61208
#define IDS_QUERY_GOOD_MOVE             61209
#define IDS_QUERY_TEST                  61210
#define IDS_FORMAT_DATE                 61211
#define IDS_WRONGPERIOD                 61212
#define IDS_HEAD_FOR_MOVE_GOODS         61213
#define IDS_FIRST_TOOLTIP               61214
#define IDS_SEC_TOOLTIP                 61215
#define IDS_THIRD_TOOLTIP               61216
#define IDS_CONNSTRING                  61217
#define IDS_DATA_IS_DIRTY               61218
#define IDR_FOLDERTAB                   61219
#define IDS_CONNSTRINGSQL               61220
#define ID_PANE_KKM_ERROR               61221

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        258
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           137
#endif
#endif
